apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo-validate-false
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/umi0410/umi0410.github.io
    targetRevision: master
    path: content/en/blog/devops/how-to-canary-deploy-argo-rollouts-when-using-argocd/code/validate-false/backend-manifest
  destination:
    name: in-cluster
    namespace: rollouts-demo-validate-false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: networking.istio.io
      kind: VirtualService
      jqPathExpressions:
        - ".spec.http[] | select(.name == \"rollouts-demo\") | .route[] | .weight"
